channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.2
- pip:
  - mlflow==2.5.0
  - numpy==1.24.0
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.1.3
  - scipy==1.14.1
  - xgboost==1.7.6
name: mlflow-env
