channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.2
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - numpy==1.24.0
  - psutil==5.9.0
  - scikit-learn==1.1.3
  - scipy==1.14.1
name: mlflow-env
